name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Run tests
        run: docker compose up --abort-on-container-exit --build

      - name: Shutdown containers
        run: docker compose down